# Generated by Django 5.2.12 on 2026-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_parentsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
