# Generated by Django 5.2.12 on 2026-03-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_subscription_tier_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
