# Generated by Django 5.2.12 on 2026-03-14

import django.db.models.deletion
from django.db import migrations, models


def map_template_assignment_types(apps, schema_editor):
    AssignmentType = apps.get_model("courses", "AssignmentType")
    CourseAssignmentTemplate = apps.get_model("planning", "CourseAssignmentTemplate")

    for template in CourseAssignmentTemplate.objects.select_related(
        "course", "assignment_type"
    ):
        legacy_type = template.assignment_type
        if legacy_type is None:
            continue

        unified = AssignmentType.objects.filter(
            course_id=template.course_id,
            name=legacy_type.name,
        ).first()

        if unified is None:
            unified = AssignmentType.objects.create(
                course_id=template.course_id,
                name=legacy_type.name,
                color=legacy_type.color,
                is_hidden=legacy_type.is_hidden,
                weight=0,
                order=legacy_type.order,
            )

        template.assignment_type_unified_id = unified.id
        template.save(update_fields=["assignment_type_unified"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("courses", "0006_assignmenttype_global_type_color_hidden"),
        ("planning", "0002_assignmentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassignmenttemplate",
            name="assignment_type_unified",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planning_templates_legacy_bridge",
                to="courses.assignmenttype",
            ),
        ),
        migrations.RunPython(map_template_assignment_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="courseassignmenttemplate",
            name="assignment_type",
        ),
        migrations.RenameField(
            model_name="courseassignmenttemplate",
            old_name="assignment_type_unified",
            new_name="assignment_type",
        ),
        migrations.AlterField(
            model_name="courseassignmenttemplate",
            name="assignment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="courses.assignmenttype",
            ),
        ),
    ]
