# Generated by Django 5.2.12 on 2026-03-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_unify_assignment_type_to_courses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseAssignmentType",
        ),
    ]
