# Generated by Django 5.2.12 on 2026-03-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_assignmenttype_default_points_available"),
        ("planning", "0005_studentassignment_graded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseassignmenttemplate",
            name="assignment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="courses.assignmenttype",
            ),
        ),
    ]
