# Generated by Django 5.2.5 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0007_assignmentcomment_assignmentsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("needs_grading", "Needs Grading"),
                    ("complete", "Complete"),
                    ("overdue", "Overdue"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
