# Generated by Django 5.2.12 on 2026-03-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_coursesubjectconfig"),
        ("curriculum", "0004_phase6_custom_groups_lpw_cap"),
        ("planning", "0011_activityprogress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("assignment", "Assignment"),
                            ("activity", "Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                ("day_number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number", "day_number", "order"],
            },
        ),
        migrations.CreateModel(
            name="LessonPlanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="courses.coursesubjectconfig",
                    ),
                ),
                (
                    "curriculum_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_details",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "plan_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_detail",
                        to="planning.planitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentPlanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_graded", models.BooleanField(default=False)),
                ("due_offset_days", models.IntegerField(default=0)),
                (
                    "assignment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_plan_details",
                        to="courses.assignmenttype",
                    ),
                ),
                (
                    "plan_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_detail",
                        to="planning.planitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityPlanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.TextField(blank=True, default="")),
                ("objective", models.TextField(blank=True, default="")),
                (
                    "unit_title",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("due_offset_days", models.IntegerField(default=0)),
                (
                    "course_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_plans",
                        to="courses.coursesubjectconfig",
                    ),
                ),
                (
                    "plan_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_detail",
                        to="planning.planitem",
                    ),
                ),
            ],
        ),
    ]
