# Generated by Django 5.2.12 on 2026-03-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0012_planitem_lessonplandetail_assignmentplandetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityprogress",
            name="new_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_progress_new",
                to="planning.planitem",
            ),
        ),
        migrations.AddField(
            model_name="studentassignment",
            name="new_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_assignments_new",
                to="planning.planitem",
            ),
        ),
    ]
