# Generated by Django 5.2.12 on 2026-03-14 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_assignmenttype_default_points_available"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentGradeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "letter_grade",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                (
                    "gpa_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("graded_assignments_count", models.PositiveIntegerField(default=0)),
                ("total_assignments_count", models.PositiveIntegerField(default=0)),
                ("missing_assignments_count", models.PositiveIntegerField(default=0)),
                ("late_assignments_count", models.PositiveIntegerField(default=0)),
                ("assignment_type_breakdown", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_summary",
                        to="courses.courseenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeScaleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Scale", max_length=100)),
                (
                    "bands",
                    models.JSONField(default=reports.models.default_grade_scale_bands),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_scale_profiles",
                        to="courses.course",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_scale_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["course_id", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "course"),
                        name="reports_unique_parent_course_grade_scale",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("course__isnull", True)),
                        fields=("parent",),
                        name="reports_unique_parent_global_grade_scale",
                    ),
                ],
            },
        ),
    ]
