# Generated by Django 5.2.12 on 2026-03-14

from django.db import migrations, models
import django.db.models.deletion


def backfill_assignmenttype_from_global(apps, schema_editor):
    AssignmentType = apps.get_model('courses', 'AssignmentType')
    GlobalAssignmentType = apps.get_model('courses', 'GlobalAssignmentType')

    for at in AssignmentType.objects.select_related('course__parent'):
        gt = GlobalAssignmentType.objects.filter(
            parent_id=at.course.parent_id,
            name=at.name,
        ).first()
        if gt:
            at.global_type_id = gt.id
            at.color = gt.color
            at.is_hidden = gt.is_hidden
        at.save(update_fields=['global_type', 'color', 'is_hidden'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttype',
            name='color',
            field=models.CharField(default='#9ca3af', max_length=7),
        ),
        migrations.AddField(
            model_name='assignmenttype',
            name='global_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='course_assignment_types',
                to='courses.globalassignmenttype',
            ),
        ),
        migrations.AddField(
            model_name='assignmenttype',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_assignmenttype_from_global, migrations.RunPython.noop),
    ]
