# Generated by Django 5.2.12 on 2026-03-28 19:03

import json

from django.db import migrations, models


def _csv_to_json_list(val):
    """Convert a CSV string like '0,2,4' to a JSON-encoded list '[0,2,4]'."""
    if val is None:
        return json.dumps([0, 1, 2, 3, 4])
    if isinstance(val, str) and not val.startswith("["):
        parts = [p.strip() for p in val.split(",") if p.strip().isdigit()]
        return json.dumps([int(p) for p in parts] or [0, 1, 2, 3, 4])
    return None  # already valid JSON, skip


def convert_course_days(apps, schema_editor):
    """Convert Course.default_days from CSV string to JSON list."""
    cursor = schema_editor.connection.cursor()
    cursor.execute("SELECT id, default_days FROM courses_course")
    for row_id, val in cursor.fetchall():
        new_val = _csv_to_json_list(val)
        if new_val is not None:
            cursor.execute(
                "UPDATE courses_course SET default_days = %s WHERE id = %s",
                [new_val, row_id],
            )


def convert_enrollment_days(apps, schema_editor):
    """Convert CourseEnrollment.days_of_week from CSV string to JSON list."""
    cursor = schema_editor.connection.cursor()
    cursor.execute("SELECT id, days_of_week FROM courses_courseenrollment")
    for row_id, val in cursor.fetchall():
        new_val = _csv_to_json_list(val)
        if new_val is not None:
            cursor.execute(
                "UPDATE courses_courseenrollment SET days_of_week = %s WHERE id = %s",
                [new_val, row_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_assignmenttype_default_points_available"),
    ]

    operations = [
        migrations.RunPython(
            convert_course_days,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            convert_enrollment_days,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="course",
            name="default_days",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="days_of_week",
            field=models.JSONField(default=list),
        ),
    ]
