# Generated by Django 5.2.12 on 2026-03-30 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_days_of_week_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSubjectConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("key_stage", models.CharField(blank=True, default="", max_length=10)),
                ("year", models.CharField(blank=True, default="", max_length=20)),
                (
                    "lessons_per_week",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("days_of_week", models.JSONField(default=list)),
                ("colour_hex", models.CharField(default="#6c757d", max_length=7)),
                (
                    "source",
                    models.CharField(
                        choices=[("oak", "Oak"), ("custom", "Custom"), ("csv", "CSV")],
                        default="oak",
                        max_length=10,
                    ),
                ),
                (
                    "source_subject_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "source_year",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_configs",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_name"],
                "unique_together": {("course", "subject_name")},
            },
        ),
    ]
