# Generated by Codex on 2026-03-31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_child_onboarding_fields"),
        ("courses", "0009_coursesubjectconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_student_workspace",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="student_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_courses",
                to="scheduler.child",
            ),
        ),
        migrations.CreateModel(
            name="CourseSubjectScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="courses.coursesubjectconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "period", "id"],
                "unique_together": {("course_subject", "weekday", "period")},
            },
        ),
    ]
