# Generated by Django 5.2.12 on 2026-03-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_stage", models.CharField(db_index=True, max_length=10)),
                ("subject_name", models.CharField(db_index=True, max_length=100)),
                ("programme_slug", models.CharField(max_length=200)),
                ("year", models.CharField(db_index=True, max_length=20)),
                ("unit_slug", models.CharField(max_length=200)),
                ("unit_title", models.CharField(max_length=300)),
                ("lesson_number", models.IntegerField()),
                ("lesson_title", models.CharField(max_length=300)),
                ("lesson_url", models.URLField(max_length=500)),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["key_stage", "subject_name", "unit_slug", "lesson_number"],
            },
        ),
    ]
