# Generated by Django 5.2.12 on 2026-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
