# Generated by Django 5.2.12 on 2026-03-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_scheduling_grid_and_custom_subjects"),
        ("scheduler", "0004_phase6_custom_groups_lpw_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="custom_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="scheduler.customsubjectgroup",
            ),
        ),
    ]
