# Generated by Django 5.2.12 on 2026-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_add_child_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolledsubject",
            name="days_of_week",
            field=models.CharField(default="0,1,2,3,4", max_length=20),
        ),
        migrations.AddField(
            model_name="enrolledsubject",
            name="source_year",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
