# Generated by Django 5.2.12 on 2026-03-28 19:01

import json

from django.db import migrations, models


def convert_enrolledsubject_days(apps, schema_editor):
    """Convert EnrolledSubject.days_of_week from CSV string to JSON list."""
    db = schema_editor.connection
    cursor = db.cursor()
    cursor.execute("SELECT id, days_of_week FROM scheduler_enrolledsubject")
    rows = cursor.fetchall()
    for row_id, days_val in rows:
        if days_val is None:
            new_val = json.dumps([0, 1, 2, 3, 4])
        elif isinstance(days_val, str) and not days_val.startswith("["):
            parts = [p.strip() for p in days_val.split(",") if p.strip().isdigit()]
            new_val = json.dumps([int(p) for p in parts] or [0, 1, 2, 3, 4])
        else:
            continue  # already valid JSON
        cursor.execute(
            "UPDATE scheduler_enrolledsubject SET days_of_week = %s WHERE id = %s",
            [new_val, row_id],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_enrolledsubject_source_subject_name"),
    ]

    operations = [
        migrations.RunPython(
            convert_enrolledsubject_days,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="enrolledsubject",
            name="days_of_week",
            field=models.JSONField(default=list),
        ),
    ]
