# Generated by Django 5.2.12 on 2026-03-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_coursesubjectconfig"),
        ("planning", "0013_activityprogress_new_plan_item_and_more"),
        ("scheduler", "0007_days_of_week_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledlesson",
            name="course_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_lessons",
                to="courses.coursesubjectconfig",
            ),
        ),
        migrations.AddField(
            model_name="scheduledlesson",
            name="plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_lessons",
                to="planning.planitem",
            ),
        ),
    ]
