# Generated by Codex on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0008_scheduledlesson_course_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="is_setup_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="child",
            name="onboarding_updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="child",
            name="birth_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="school_year",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
