# Generated by Codex on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_child_onboarding_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="onboarding_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
